### ISSUE TITLE
handling abort in useAsyncTask start().then

### ISSUE THREAD

**Issue by clarkbynum** [dai-shi/react-hooks-async#45]
Hi, thank you very much for this library, it has simplified and standardized how I fetch things. I'm running into a little confusion with the types returned by the start function in useAsyncTask. The types show it typed as `start: (...args: Args) => Promise<Result | symbol>;` If a symbol is returned does that mean the request was aborted? Here's a codesandbox which illustrates the problem: https://codesandbox.io/s/wild-browser-f9nuq?file=/src/App.tsx

The relevant code starts on line 35 - 
```
onClick={() =>
          start(id).then((data) => {
            if (typeof data === "symbol") {
              return; // data is of type symbol, does this mean the request was aborted?
            }
            console.log(data); // data is of type Post
          })
        }
```

**Comment by dai-shi** [comment]
Hey, thanks for trying.

Yeah, the symbol is for the aborted state.
https://github.com/dai-shi/react-hooks-async/blob/88b1d614b1ac5c7e46b164d88409f5298e1ffa8f/src/use-async-task.js#L3

It's not exported because it's mainly for internal use. But, in your use case, you would need to like that. Only the problem is if `Result` includes other symbols, which should be rare.

So, in summary, because using the return value of `start` is not the main use case, it's not documented. Your use case is valid and the workaround is valid for now. Meanwhile, I should think if I should export the symbol...

**Comment by clarkbynum** [comment]
Ok, thanks for the validation. I originally tried to import that symbol but, as you mentioned, noticed that it wasn't being exported. I don't have a need to differentiate between SYMBOL_ABORTED and my return types since none of my fetch functions return a symbol. Thanks for the quick response!
